apiVersion: v1
kind: Pod
metadata:
  name: argocd-myapp
  namespace: suraj-space
  labels:
    name: argocd-myapp
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
